name: Update README with Markscribe

on:
  schedule:
    # Runs at the top of every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants the action permission to commit the new README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install taciturnaxolotl/markscribe
        run: go install github.com/taciturnaxolotl/markscribe@latest

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HACKATIME_API_KEY: ${{ secrets.HACKATIME_API_KEY }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_BASE_URL: "https://hackatime.hackclub.com/api/v1"
        run: |
          markscribe -write README.md templates/README.md.tpl

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated markscribe hackatime data"
          branch: main
          file_pattern: README.md